### ISSUE TITLE
bug: failed with duplicated tx 

### ISSUE THREAD

**Issue by 0xrzls** [kkrt-labs/kakarot-rpc#1184] opened 2024-06-12 15:29 UTC
# Bug Report

when interacting with a our factory contract with a bulk tx cannot be done submited an unreadable gas causes the rpc call to fail, the problem is on  the correction and gas readings  

```
Failed to deploy ; 
{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32603,"message":"starknet provider error: StarknetError(DuplicateTx)","cause":null},"transaction":{"nonce":0,"gasPrice":{"type":"BigNumber","hex":"0x01"},"gasLimit":{"type":"BigNumber","hex":"0x0186a0"},"to":null,"value":{"type":"BigNumber","hex":"0x00"},"data":"0x604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3","chainId":1802203764,"v":3604407563,"r":"0x2222222222222222222222222222222222222222222222222222222222222222","s":"0x2222222222222222222222222222222222222222222222222222222222222222","from":"0x49A729f6F90d3a60db1d8A42D2716bed88154B4D","hash":"0x9c9a59b30405168719a8b8bc33b73427b31be519e10b98955a56a88063ead72f","type":null,"confirmations":0},"transactionHash":"0x9c9a59b30405168719a8b8bc33b73427b31be519e10b98955a56a88063ead72f"}
```

**Comment by greged93** [comment] 2024-06-24 07:41
this should be fixed on the latest release, can you check. I'm closing in the meantime because the issue cannot be reproduced.

**Closed by greged93** 2024-06-24 07:41 UTC
Labels: bug
